Dp 23300 permission change for topic pages 4
massgov/openmass pull request #1186
Opened 2021-11-25 21:36 UTC by beto-aveiga

**Description:**
Explain the technical implementation of the work done.

**Jira:** (Skip unless you are MA staff)
DP-****

**To Test:**
- [ ] Add steps to test this feature

---

[Peer Review Checklist](https://github.com/massgov/openmass/blob/develop/docs/peer_review_checklist.md)

2021-11-29 20:07 UTC, weekbeforenext approved these changes
One nitpick comment, but this seems good. Going to test on Tugboat before merge.

2021-11-29 20:07 UTC, weekbeforenext commented on docroot/modules/custom/mass_fields/mass_fields.module
> +    is_array($element) && (isset($element['#access']) || isset($element['#type'])) ?
It might be worth writing this conditional similar to the previous one, for ease of reading. Wouldn't affect functionality, so more of a nitpick.

2021-11-29 20:20 UTC, weekbeforenext requested changes
As an Author/Editor user on Tugboat, the field restrictions look right, but I can't save the node.

2021-11-29 22:24 UTC, beto-aveiga commented on docroot/modules/custom/mass_fields/mass_fields.module
> +    is_array($element) && (isset($element['#access']) || isset($element['#type'])) ?
I just saw your comment. 
Sure, Thanks, I agree, indeed.
However, I think I changed that code already, and I can't find that pattern now.

2021-11-29 22:29 UTC, beto-aveiga commented
Thanks! @weekbeforenext it seems that when I moved to a new branch based on feature/DP-22668_topic-page-redesign, I lost a few things. I improved the test, and now it checks saving topic pages as well.

2021-11-30 01:32 UTC, weekbeforenext approved these changes

2021-11-30 01:33 UTC, merged