Dp 24326 promo page permissions updates
massgov/openmass pull request #1495
Opened 2022-05-05 21:32 UTC by beto-aveiga

**Description:**
      - Not require unpublished date for promotional pages
      - KPI fields not required on promo pages
      - Delete role campaign_landing_page_publisher

**Jira:** (Skip unless you are MA staff)
DP-24326

---

[Peer Review Checklist](https://github.com/massgov/openmass/blob/develop/docs/peer_review_checklist.md)

2022-05-09 14:24 UTC, weitzman requested changes

2022-05-09 14:24 UTC, weitzman commented on docroot/modules/custom/mass_scheduled_transitions/mass_scheduled_transitions.module
>  define('MASS_SCHEDULED_TRANSITIONS_CAMPAIGN_LANDING_MAX_DURATION', '14 months');
I dont think this needs its own max duration anymore. Treated like other content?

2022-05-11 18:54 UTC, beto-aveiga commented on docroot/modules/custom/mass_scheduled_transitions/mass_scheduled_transitions.module
>  define('MASS_SCHEDULED_TRANSITIONS_CAMPAIGN_LANDING_MAX_DURATION', '14 months');
I don't understand the question or what to do. 

I see 2 references to that constant on `docroot/modules/custom/mass_scheduled_transitions/mass_scheduled_transitions.module`.

2022-05-13 12:09 UTC, weitzman commented on docroot/modules/custom/mass_scheduled_transitions/mass_scheduled_transitions.module
>  define('MASS_SCHEDULED_TRANSITIONS_CAMPAIGN_LANDING_MAX_DURATION', '14 months');
OK, we dont have to change this now as the Jira ticket doesnt mention this policy changing.

2022-05-13 12:10 UTC, weitzman approved these changes

2022-05-13 14:16 UTC, merged