DP-26299: Update page/org alert rendering to include Updated
massgov/openmass pull request #1767
Opened 2022-11-01 08:28 UTC by arthurbaghdas

**Description:**
Explain the technical implementation of the work done.

**Jira:** (Skip unless you are MA staff)
DP-26299

**To Test:**
- [ ] Add steps to test this feature

---

[Peer Review Checklist](https://github.com/massgov/openmass/blob/develop/docs/peer_review_checklist.md)

2022-11-01 15:01 UTC, weitzman requested changes
If we ever translate the site, it is helpful to give translator context about how a string is used.

2022-11-01 15:01 UTC, weitzman commented on docroot/modules/custom/mass_alerts/src/Controller/AlertsController.php
> +        $alert['suffix'] = $this->t('Updated ') . $timestamp;
```suggestion
        $alert['suffix'] = $this->t('Updated @timestamp', ['@timestamp' => $timestamp]);
```

2022-11-02 06:32 UTC, arthurbaghdas commented on docroot/modules/custom/mass_alerts/src/Controller/AlertsController.php
> +        $alert['suffix'] = $this->t('Updated ') . $timestamp;
Thanks for the note, all set.

2022-11-03 13:52 UTC, weitzman approved these changes

2022-11-03 13:52 UTC, merged