DP-28475: Add testing so that we validate that Google Tag Manager code is actually inserted onto the pages
massgov/openmass pull request #2083
Opened 2023-06-12 12:07 UTC by arthurbaghdas

**Description:**
Explain the technical implementation of the work done.

**Jira:** (Skip unless you are MA staff)
DP-28475

**To Test:**
- [ ] Add steps to test this feature

---

[Peer Review Checklist](https://github.com/massgov/openmass/blob/develop/docs/peer_review_checklist.md)

2023-06-12 14:49 UTC, weitzman commented
What is the benefit of testing on a random node? I would test on one QAG page (any node type). That shows coverage for an entity page and the home page. This also gets testing code out of our non-testing codebase (the new alter hook).

2023-06-13 07:44 UTC, arthurbaghdas commented
> What is the benefit of testing on a random node? I would test on one QAG page (any node type). That shows coverage for an entity page and the home page. This also gets testing code out of our non-testing codebase (the new alter hook). Further, it prevents us from hitting nodes whose content is in a rabbit hole (see rabbit hole module)
> 
> Otherwise this looks good.

Ticket says: `We could test against a random published node of a random type.`

2023-06-13 12:51 UTC, weitzman commented
Thats an unfortunate suggestion in the ticket description. IMO it is the job of the developer to highlight problems in issue description.

This PR approach contradicts our testing docs at https://github.com/massgov/openmass/blob/develop/docs/testing.md#tips which say "Robust tests create and delete their own content. Relying on production content is brittle.". This PR is even more brittle since it relies on *random* production content. If the test fails it might pass on a subsequent run. And vice versa.

I suggest creating own content, or if you must use existing content, use a QAG node. I will pass the PR when it doesnt test a random node.

2023-06-13 13:11 UTC, arthurbaghdas commented
Changed

2023-06-13 13:49 UTC, weitzman commented on docroot/modules/custom/mass_content/tests/src/ExistingSiteJavascript/GoogleTagManagerTest.php
> +  const QAG_PATHS = [
Does the GTM insertion code actually vary by path or content type? If yes, then this looks good. If no, we dont need to slow down tests by making 20 requests. One path suffices and is faster.

2023-06-13 14:09 UTC, arthurbaghdas commented on docroot/modules/custom/mass_content/tests/src/ExistingSiteJavascript/GoogleTagManagerTest.php
> +  const QAG_PATHS = [
We are just making one request to one random path from the list
https://github.com/massgov/openmass/pull/2083/files#diff-16846f87bed735aee0f5335810c2ec167b74798249adbd4c95388338d663e501R53

I'm not sure about the differences. So I guess 1 check for Homepage and 1 check for another page as the ticket says should be good.

2023-06-13 20:46 UTC, weitzman commented
Sorry I misread. As you say performance is not an issue. 

We have updated our testing docs to discourage randomness. See https://github.com/massgov/openmass/pull/2085. It creates a situation where a test fails and then a retry with the same code passes. I would prefer if we follow the best practice as per the testing docs that I linked to. That is, to create content and then test that new node.

2023-06-14 05:45 UTC, arthurbaghdas commented
Ok done

2023-06-14 13:54 UTC, weitzman requested changes

2023-06-14 13:54 UTC, weitzman commented on docroot/modules/custom/mass_content/tests/src/ExistingSiteJavascript/GoogleTagManagerTest.php
> +    var_dump($node->toUrl()->toString());
```suggestion
```

2023-06-14 14:18 UTC, weitzman approved these changes

2023-06-14 14:19 UTC, merged