DP-35609: Change sitewide alert notifications to only send emails when an alert is published or transitioned out of published state
massgov/openmass pull request #2731
Opened 2024-10-29 07:12 UTC by arthurbaghdas

**Description:**
Explain the technical implementation of the work done.

**Jira:** (Skip unless you are MA staff)
DP-****

**To Test:**
- [ ] Add steps to test this feature

---

[Peer Review Checklist](https://github.com/massgov/openmass/blob/develop/docs/peer_review_checklist.md)

2024-10-29 07:13 UTC, tom-fleming commented
<!--
  1 failure:  Add a changelog Y...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Add a changelog YAML file to this PR</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3862af0fc2979c21cfe41ddc17cf120530e471b5
</p>

2024-11-14 14:25 UTC, weitzman requested changes

2024-11-14 14:25 UTC, weitzman commented on docroot/modules/custom/mass_alerts/mass_alerts.module
> +    $current_state = $node->moderation_state->value;
Lets use \Drupal\mass_content_moderation\MassModerationTrait::getModerationState. Same for the original state

2024-11-18 05:38 UTC, arthurbaghdas commented on docroot/modules/custom/mass_alerts/mass_alerts.module
> +    $current_state = $node->moderation_state->value;
Done

2024-11-18 21:33 UTC, merged