DP-36332: Login links integration branch
massgov/openmass pull request #2787
Opened 2024-12-23 08:18 UTC by arthurbaghdas

**Description:**
Explain the technical implementation of the work done.

**Jira:** (Skip unless you are MA staff)
DP-****

**To Test:**
- [ ] Add steps to test this feature

---

[Peer Review Checklist](https://github.com/massgov/openmass/blob/develop/docs/peer_review_checklist.md)

2024-12-23 08:19 UTC, tom-fleming commented
<!--
  1 failure:  Add a changelog Y...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Add a changelog YAML file to this PR</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against fdde3f47517d1f877911a2a6d7c1c5d1cf02dbf5
</p>

2025-02-21 00:24 UTC, dstorozhuk commented on docroot/themes/custom/mass_theme/mass_theme.theme
> +          if ($node->id() != 4206) {
@arthurbaghdas how node 4206 is that special? 

if there are any other way to define this node as a special (site configs, yml files, node it self with some field etc)?

2025-02-24 06:16 UTC, arthurbaghdas commented on docroot/themes/custom/mass_theme/mass_theme.theme
> +          if ($node->id() != 4206) {
No need for that, that's an old way of adding global login links, I've removed this code, since we no longer show global login links that are defined in node 4206

2025-02-24 14:33 UTC, tom-fleming requested changes, later dismissed

2025-02-24 14:33 UTC, tom-fleming commented on docroot/modules/custom/mass_content/src/Drush/Commands/MassContentCommands.php
> +   * @command mass-content:set-login-links-options
@arthurbaghdas This command is failing locally for me with `Field field_login_links_options is unknown.` Is there a manual step required before running this step?

2025-03-03 22:55 UTC, clairesunstudio commented
Pushed up a final mayflower change for mobile style --> https://github.com/massgov/mayflower/pull/1943/commits/d0b0d6bb085f1e2dcc387cb9064c09963ac113ce waiting to update here

Also, when the page banner has a solid background, regardless content types, please use primary white button style to avoid hover state color collision with the background. For example, info details and binder can both have solid colored background, so they should use different button styles based on if the page banner is white or filled with color.

Issue page: https://feature3.edit.mass.gov/audit/qag-binderaudit
desired button styles: 
- https://feature3.edit.mass.gov/ezdrivema (with background color)
- https://feature3.edit.mass.gov/info-details/qaginfo-details-image-in-section-left-align-with-no-text-wrap (with white background)


Deployment to feature3 is breaking the dropdowns. No links are visible when clicking on the button.
Testing URLs:
https://feature3.edit.mass.gov/audit/qag-binderaudit
https://feature3.edit.mass.gov/info-details/qaginfo-details-image-in-section-left-align-with-no-text-wrap
https://feature3.edit.mass.gov/orgs/qag-organization-boards
https://feature3.edit.mass.gov/ezdrivema
https://feature3.edit.mass.gov/lists/rmv-forms-and-applications

2025-03-06 17:34 UTC, arthurbaghdas commented
> Pushed up a final mayflower change for mobile style --> [massgov/mayflower@d0b0d6b](https://github.com/massgov/mayflower/commit/d0b0d6bb085f1e2dcc387cb9064c09963ac113ce).
> 
> Also, when the page banner has a solid background, regardless content types, please use primary white button style to avoid hover state color collision with the background. For example, info details and binder can both have solid colored background, so they should use different button styles based on if the page banner is white or filled with color.
> 
> Issue page: https://feature3.edit.mass.gov/audit/qag-binderaudit
> 
> > Note: you have fixed this for info details with colored background https://feature3.edit.mass.gov/info-details/moor-blog-posts)
> > desired button styles:
> 
> * https://feature3.edit.mass.gov/ezdrivema (with background color)
> * https://feature3.edit.mass.gov/info-details/qaginfo-details-image-in-section-left-align-with-no-text-wrap (with white background)
> 
> Deployment to feature3 is breaking the dropdowns. No links are visible when clicking on the button. Testing URLs: https://feature3.edit.mass.gov/audit/qag-binderaudit https://feature3.edit.mass.gov/info-details/qaginfo-details-image-in-section-left-align-with-no-text-wrap https://feature3.edit.mass.gov/orgs/qag-organization-boards https://feature3.edit.mass.gov/ezdrivema https://feature3.edit.mass.gov/lists/rmv-forms-and-applications

fixed, you can review on feature5

2025-03-10 17:51 UTC, tom-fleming commented
LGTM!

2025-03-10 17:51 UTC, merged