Upgrade to Acquia Cloud API 2
massgov/openmass pull request #52
Opened 2019-12-19 16:41 UTC by weitzman

- Depends on https://github.com/massgov/DS-Infrastructure/pull/189. Lets merge that first.

**Jira:**
https://jira.mass.gov/browse/DP-****

**To Test:**
- [ ] Get new drush aliases file from DS-Infrastructure. See https://github.com/massgov/DS-Infrastructure/pull/189
- [ ] Populate 2 new .env variables. See env.example change
- [ ] Push this branch to feature5 using ma:deploy. Assure it succeeds.

---

[Peer Review Checklist](https://github.com/massgov/opemass/blob/develop/docs/peer_review_checklist.md)

2019-12-20 19:00 UTC, rbayliss requested changes
This looks awesome!  My only request is to use a stable version of acquia-php-sdk-v2.

2019-12-20 19:00 UTC, rbayliss commented on composer.json
> +        "typhonius/acquia-php-sdk-v2": "1.1.x-dev",
Can we constrain this to stable releases, or is there a specific reason we need to be on dev? If there isn't a particular reason, how about if we switch to `~1.1`?

2019-12-20 19:08 UTC, rbayliss commented
I did check that the aliases were right, that this deploys cleanly, and that `ma:latest-backup-url` still works.  Everything checks out, but I still think we might want to wait until after the holidays to merge so we don't put ourselves in a position of having nobody around to support a problematic release.  But I'm good to go with these changes as soon as folks are back.

2019-12-21 12:34 UTC, weitzman commented on composer.json
> +        "typhonius/acquia-php-sdk-v2": "1.1.x-dev",
There is no release yet with https://github.com/typhonius/acquia-php-sdk-v2/pull/36 in it.

2019-12-23 22:03 UTC, typhonius commented on composer.json
> +        "typhonius/acquia-php-sdk-v2": "1.1.x-dev",
I'm planning on releasing a new tag for both 1.1 and 2.0 branches over the holiday period if that would help!

2019-12-26 08:49 UTC, typhonius commented on composer.json
> +        "typhonius/acquia-php-sdk-v2": "1.1.x-dev",
1.1.1 and 2.0.1 have been released if you'd like to pin to those. Both have notifications built in so should be of use in this PR. I'll mostly be working in the 2.x branch now as it's been rewritten to fulfil the growing needs of the library.

2019-12-31 15:17 UTC, rbayliss commented on composer.json
> +        "typhonius/acquia-php-sdk-v2": "1.1.x-dev",
@typhonius, thanks for the update!  Very helpful.

2019-12-31 15:55 UTC, yriahi commented on composer.json
> +        "typhonius/acquia-php-sdk-v2": "1.1.x-dev",
I have now required `~1.1`. Thank you!

2019-12-31 16:21 UTC, rbayliss commented
Ah - actually, I just realized that we need to update `docker-compose.yml` and `.circleci/mysql-rebuild/docker-compose.yml` to use the new environment variables. Let's keep both the `AC_API_*` and `AC_API2_*` variables in there and clean up the `AC_API_*` ones in a followup.

2019-12-31 16:58 UTC, yriahi commented
@rbayliss I made the change to preserve both environment variables - Acquia Cloud v1 and v2.

2019-12-31 17:50 UTC, merged