DP-20892 Responsive iframe height
massgov/openmass pull request #605
Opened 2021-02-09 14:58 UTC by tom-fleming

**Description:**
Explain the technical implementation of the work done.

**Jira:** (Skip unless you are MA staff)
https://jira.mass.gov/browse/DP-20892

**To Test:**
- [ ] Add steps to test this feature

**Screenshots/GIFs:**
Use something like [licecap](http://www.cockos.com/licecap/) to capture gifs to demonstrate behaviors.

---

[Peer Review Checklist](https://github.com/massgov/openmass/blob/develop/docs/peer_review_checklist.md)

2021-03-01 20:52 UTC, clairesunstudio commented on docroot/themes/custom/mass_theme/overrides/js/iframe_resizer_iframe.js
> +  console.log('dklsmflksmfkldsmf');
```suggestion
```

2021-03-01 20:52 UTC, clairesunstudio commented on docroot/themes/custom/mass_theme/overrides/js/iframe_resizer_parent.js
> +  console.log(matches);
```suggestion
```

2021-04-22 21:20 UTC, clairesunstudio commented
Updated iframe example: https://massgov.github.io/mg_utility/flex_height_embed.html
Created a test page on feature 4: https://massgovfeature4.prod.acquia-sites.com/info-details/iframe-flex-height-test

2 issues noticed:
1. The iframe on the test page keeps creating empty spaces to pushing down the content below 
2. Comparing the code: Previously it posts on window mutation observe vs now it seems to only post on window load and resize. I think it needs to detect the dom change for dynamic content to work

2021-04-22 21:20 UTC, clairesunstudio requested changes, later dismissed
Updated iframe example: https://massgov.github.io/mg_utility/flex_height_embed.html
Created a test page on feature 4: https://massgovfeature4.prod.acquia-sites.com/info-details/iframe-flex-height-test

2 issues noticed:
1. The iframe on the test page keeps creating empty spaces to pushing down the content below 
2. Comparing the code: Previously it posts on window mutation observe vs now it seems to only post on window load and resize. I think it needs to detect the dom change for dynamic content to work

2021-04-27 16:06 UTC, clairesunstudio commented
@tom-fleming Updated JS files to match the original code and added some instructions. Can you test this locally?
If it works, please push it up to feature4 --> https://massgovfeature4.prod.acquia-sites.com/info-details/iframe-flex-height-test

2021-04-29 17:04 UTC, clairesunstudio commented
Fixed eslint errors and re-deployed to feature4

2021-04-30 14:11 UTC, clairesunstudio commented on conf/drupal/config/field.storage.paragraph.field_iframe_height_config.yml
> +      label: '100% (as much height as necessary to show the whole iframe without scrolling within the frame). <strong>If you want the iframe height to adjust based on the content in your iframe, choo
```suggestion
      label: '100% (as much height as necessary to show the whole iframe without scrolling within the frame). <strong>If you want the iframe height to adjust based on the content in your iframe, choose 100% and add the following script into your iframe HTML source code before the closing body tag:
<code>"<script type="text/javascript" src="https://mass.gov/themes/custom/mass_theme/overrides/js/iframe_resizer_iframe.js"></script>"<code>.</strong>'
```

2021-04-30 14:16 UTC, clairesunstudio commented on conf/drupal/config/field.storage.paragraph.field_iframe_height_config.yml
> +      label: '100% (as much height as necessary to show the whole iframe without scrolling within the frame). <strong>If you want the iframe height to adjust based on the content in your iframe, choo
I think it will be more straightforward to ask the authors to add the CDN version

2021-04-30 18:56 UTC, tom-fleming commented on conf/drupal/config/field.storage.paragraph.field_iframe_height_config.yml
> +<pre><code>&lt;script type="text/javascript" src="https://mass.gov/themes/custom/mass_theme/overrides/js/iframe_resizer_iframe.js"&gt;&lt;/script&gt;<code></pre>.</strong>'
```suggestion
</strong><pre><code>&lt;script type="text/javascript" src="https://mass.gov/themes/custom/mass_theme/overrides/js/iframe_resizer_iframe.js"&gt;&lt;/script&gt;<code></pre>'
```

2021-05-05 21:07 UTC, tom-fleming commented on conf/drupal/config/field.storage.paragraph.field_iframe_height_config.yml
> +<pre><code>&lt;script type="text/javascript" src="https://mass.gov/themes/custom/mass_theme/overrides/js/iframe_resizer_iframe.js"&gt;&lt;/script&gt;<code></pre>'
```suggestion
<pre><code>&lt;script type="text/javascript" src="https://www.mass.gov/themes/custom/mass_theme/overrides/js/iframe_resizer_iframe.js"&gt;&lt;/script&gt;<code></pre>'
```

2021-05-05 21:07 UTC, tom-fleming commented on docroot/themes/custom/mass_theme/overrides/js/iframe_resizer_iframe.js
> +** Mass.gov CDN: https://mass.gov/themes/custom/mass_theme/overrides/js/iframe_resizer_iframe.js
```suggestion
** Mass.gov CDN: https://www.mass.gov/themes/custom/mass_theme/overrides/js/iframe_resizer_iframe.js
```

2021-05-05 21:07 UTC, tom-fleming commented on docroot/themes/custom/mass_theme/overrides/js/iframe_resizer_iframe.js
> +** <script type="text/javascript" src="https://mass.gov/themes/custom/mass_theme/overrides/js/iframe_resizer_iframe.js"></script>
```suggestion
** <script type="text/javascript" src="https://www.mass.gov/themes/custom/mass_theme/overrides/js/iframe_resizer_iframe.js"></script>
```

2021-06-24 19:18 UTC, oknate approved these changes
I tested locally and this works as expected.

2021-06-28 14:35 UTC, merged