Add script to allow easily turning xdebug off.
massgov/openmass pull request #790
Opened 2021-06-09 00:32 UTC by oknate

**Description:**
I noticed the docker is very slow, and that xdebug is enabled by default in the image.  It ignores the XDEBUG_ENABLE environment variable.  Xdebug slows down PHP, but it is very useful.  Based on a concept from the ddev command `ddev xdebug on` and `ddev xdebug off`, I added a script and ahoy command to turn xdebug on and off.

Ideally, it would be off by default, but I haven't figured out how to do that yet.  I'm not sure how to update the docker image to respect he XDEBUG_ENABLE environment variable.  But this will provide a workaround, as well as a useful tool when Xdebug is enabled.  By commenting out the plugin and restarting apache, you can turn it on and off.

In my testing, this sped up the content page initial load http://mass.local/admin/content from 8 seconds to 4 seconds and reloads from 7 seconds to about a second.

Other pages such as the status page wouldn't even load within the docker, and with xdebug disabled, they do.

**Jira:** (Skip unless you are MA staff)
https://jira.mass.gov/browse/DP-****

**To Test:**
- [ ] Add steps to test this feature

**Screenshots/GIFs:**
Use something like [licecap](http://www.cockos.com/licecap/) to capture gifs to demonstrate behaviors.

---

[Peer Review Checklist](https://github.com/massgov/openmass/blob/develop/docs/peer_review_checklist.md)

2021-06-11 18:20 UTC, weekbeforenext commented
Works for me. I like the ability to toggle xdebug. I approve :)

2021-06-14 15:34 UTC, weitzman requested changes

2021-06-14 15:34 UTC, weitzman commented on .env.example
> +# Uncomment to enable XDebug (Currently not working, always enabled in image).
lets remove this diff

2021-06-14 15:34 UTC, weitzman commented on README.md
> +
lets remove this diff

2021-06-14 15:34 UTC, weitzman commented on composer.json
> +        "drupal/csv_field": "^1.0@alpha",
unrelated

2021-06-14 15:34 UTC, weitzman commented on composer.lock
> +            "name": "drupal/csv_field",
unrelated

2021-06-14 15:34 UTC, weitzman commented on .ahoy.yml
> +    usage: Turn xdebug "on" or "off"
```suggestion
    usage: Pass "on" or "off" to enable or disable Xdebug
```

2021-06-15 15:25 UTC, closed without merging

2021-06-15 15:26 UTC, oknate commented
I'm going to open a new PR that's not from a fork.